# Generated by Django 2.2.5 on 2020-03-30 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='学号')),
                ('grade', models.CharField(max_length=20, verbose_name='班级')),
                ('score_1', models.CharField(blank=True, max_length=10, verbose_name='成绩1')),
                ('score_2', models.CharField(blank=True, max_length=10, verbose_name='成绩2')),
                ('score_3', models.CharField(blank=True, max_length=10, verbose_name='成绩3')),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact',
                'db_table': 'tb_users',
            },
        ),
    ]
