# Generated by Django 2.2.5 on 2020-04-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '学生表'},
        ),
    ]
