# Generated by Django 2.2.5 on 2020-03-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('p', models.CharField(max_length=150, verbose_name='p')),
                ('content', models.TextField(verbose_name='内容')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章',
                'db_table': 'tb_course',
                'ordering': ['-update_time', '-id'],
            },
        ), ]
