# Generated by Django 2.2.5 on 2020-03-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='标题')),
                ('content', models.TextField(verbose_name='选题')),
                ('wor', models.IntegerField(verbose_name='答案')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name': '题目',
                'db_table': 'tb_exam',
                'ordering': ['-update_time', '-id'],
            },
        ),
    ]
