# Generated by Django 2.2.5 on 2020-03-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200326_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='A',
            field=models.TextField(blank=True, default=None, verbose_name='选题A'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='B',
            field=models.TextField(blank=True, default=None, verbose_name='选题B'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='C',
            field=models.TextField(blank=True, default=None, verbose_name='选题C'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='D',
            field=models.TextField(blank=True, default=None, verbose_name='选题D'),
        ),
    ]
